--Enable database vault

SELECT
    *
FROM
    DBA_DV_STATUS;

CREATE USER DVOWNER IDENTIFIED BY Oracle123;

CREATE USER DVMANAGER IDENTIFIED BY Oracle123;

GRANT CREATE SESSION TO DVOWNER;

GRANT CREATE SESSION TO DVMANAGER;

BEGIN
    CONFIGURE_DV(
        DVOWNER_UNAME => 'dvowner',
        DVACCTMGR_UNAME => 'dvmanager'
    );
END;
/

--As dvowner
EXEC DBMS_MACADM.ENABLE_DV;

--AS SYSDBA
@?/RDBMS/ADMIN/UTLRP.SQL

ALTER PLUGGABLE DATABASE DBWORLD CLOSE IMMEDIATE;

ALTER PLUGGABLE DATABASE DBWORLD OPEN;

SELECT
    *
FROM
    DBA_DV_STATUS;

--Create a security realm to block sensitive data from privileged users as DBA
SELECT
    *
FROM
    EMPOLYEESEARCH_PROD.DEMO_HR_SUPPLEMENTAL_DATA;

--as dvowner
BEGIN
    DVSYS.DBMS_MACADM.CREATE_REALM(
        REALM_NAME => 'PROTECT_EMPLOYEESEARCH_PROD',
        DESCRIPTION => 'A mandatory realm to protect the EMPLOYEESEARCH_PROD schema',
        ENABLED => DBMS_MACUTL.G_YES,
        AUDIT_OPTIONS => DBMS_MACUTL.G_REALM_AUDIT_FAIL,
        REALM_TYPE => 1
    );
END;
/

BEGIN
    DVSYS.DBMS_MACADM.ADD_OBJECT_TO_REALM(
        REALM_NAME => 'PROTECT_EMPLOYEESEARCH_PROD',
        OBJECT_OWNER => 'EMPLOYEESEARCH_PROD',
        OBJECT_NAME => '%',
        OBJECT_TYPE => '%'
    );
END;
/

BEGIN
    DVSYS.DBMS_MACADM.ADD_AUTH_TO_REALM(
        REALM_NAME => 'PROTECT_EMPLOYEESEARCH_PROD',
        GRANTEE => 'EMPLOYEESEARCH_PROD',
        RULE_SET_NAME => '' .AUTH_OPTIONS => '1'
    );
END;
/

--now try to access the data as: employeesearch_prod, russ, SYS

SELECT
    *
FROM
    EMPLOYEESEARCH_PROD.DEMO_HR_SUPPLEMENTAL_DATA;