CREATE TABLESPACE TESTCLEAR DATAFILE '/home/oracle/testclear01.dbf' SIZE 2M;

CREATE TABLESPACE TESTENCRYPT DATAFILE '/home/oracle/testencrypt01.dbf' SIZE 2M ENCRYPTION USING 'AES256' ENCRYPT;

CREATE TABLE RUSS.TESTCLEAR (
    NAME VARCHAR2(50)
) TABLESPACE TESTCLEAR;

CREATE TABLE RUSS.TESTENCRYPT (
    NAME VARCHAR(50)
) TABLESPACE TESTENCRYPT;

INSERT INTO RUSS.TESTCLEAR VALUES (
    'TESTCLEARRUSSWASHERE'
);

INSERT INTO RUSS.TESTENCRYPT VALUES (
    'TESTENRYPTRUSSWASHERE'
);

COMMIT;

ALTER SYSTEM CHECKPOINT;

SELECT
    *
FROM
    RUSS.TESTCLEAR;

SELECT
    *
FROM
    RUSS.TESTENCRYPT;